version: '3.1'
services:
  mysql:
    image: mysql:8.2.0
    platform: linux/arm64
    container_name: mysql
    restart: always
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: nfcoffee
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - .db/mysql/data:/var/lib/mysql

